# Generated by Django 4.2.9 on 2024-01-28 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_carrera', models.CharField(max_length=40)),
                ('ciudad', models.CharField(max_length=40)),
                ('pais', models.CharField(max_length=20)),
                ('distancia', models.FloatField()),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Gear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_gear', models.CharField(max_length=20)),
                ('modelo_gear', models.CharField(max_length=60)),
                ('marca', models.CharField(max_length=20)),
                ('precio', models.FloatField()),
            ],
        ),
    ]
